### ISSUE TITLE
apply_patch.py execute permission

### ISSUE THREAD

**Issue by rfisher001** [nuagenetworks/nuage-ospdirector#12]
Please change the permissions on apply_patch.py to execute, in the OSPD13 branch

**Comment by sunny-verma** [comment]
@rfisher001 Can you please be more specific what kind of permission are we talking about here ?

**Comment by rfisher001** [comment]
I am sorry, I was wrong. I am so used to running the script without having to put python in front of it that I opened this before I figured out what the real problem was. I guess my suggestion would be to change the permissions to executable and add #!/bin/python to the first line of the script. It doesn't matter, it just makes it consistent with other python scripts that your team is putting out.

**Comment by sunny-verma** [comment]
Done.
