### ISSUE TITLE
Nuage-failed-overcloud-deployment-debug-script

### ISSUE THREAD

**Issue by jfargen-rh** [nuagenetworks/nuage-ospdirector#126]
So that overcloud stacks that aren't named overcloud can be handled with out issue in the wiki  https://github.com/nuagenetworks/nuage-ospdirector/wiki/Nuage-failed-overcloud-deployment-debug-script change the line from:
`openstack stack failures list overcloud` 
to 
`openstack stack failures list $(openstack stack list -f value -c 'Stack Name')`

**Comment by sunny-verma** [comment]
Thanks for the feedback. We have changed it. Thanks.
