### ISSUE TITLE
Nuage-failed-overcloud-deployment-debug-script ssh invocation

### ISSUE THREAD

**Issue by jfargen-rh** [nuagenetworks/nuage-ospdirector#127]
Please update the script Nuage-failed-overcloud-deployment-debug-script in the wiki https://github.com/nuagenetworks/nuage-ospdirector/wiki/Nuage-failed-overcloud-deployment-debug-script so that ssh commands ignores host-key-checks and omits the motd. This can be achieved by adding the following to the ssh invocations in the script `-o StrictHostKeyChecking=no -q`.

Here is an example:
`ssh -o StrictHostKeyChecking=no -q heat-admin@$NODE`

**Comment by sunny-verma** [comment]
Thanks for the feedback. We have changed it. Thanks.

**Comment by psairam** [comment]
As the changes are made and available at https://github.com/nuagenetworks/nuage-ospdirector/wiki/Nuage-failed-overcloud-deployment-debug-script, closing this issue.
