### ISSUE TITLE
overcloud deployment issue AVRS due to nuage-puppet-modules-6.3.0?

### ISSUE THREAD

**Issue by sacckth** [nuagenetworks/nuage-ospdirector#132]
Deployment of overcloud with AVRS computes fails using nuage-puppet-modules-6.3.0          

RHEL AVRS COMPUTE:

Openstack version is Queens (RHOSP13)
Nuage version: 6.0.7

[root@overcloud-computeavrs-0 heat-admin]# rpm -qa | grep nuage
selinux-policy-nuage-6.0.7-263.el7.x86_64
nuage-bgp-6.0.7-275.x86_64
nuage-openstack-neutronclient-6.5.0-6.0.7_274_nuage.noarch
selinux-policy-nuage-avrs-6.0.7-263.el7.x86_64
nuage-metadata-agent-6.0.7-274.el7.x86_64
**nuage-puppet-modules-6.3-0.x86_64**
nuage-openvswitch-6wind-6.0.7-274.el7.x86_64
python-openvswitch-nuage-6.0.7-274.el7.x86_64
[root@overcloud-computeavrs-0 heat-admin]# cat /etc/system-release
**Red Hat Enterprise Linux Server release 7.7 (Maipo)**
[root@overcloud-computeavrs-0 heat-admin]#
        

[overcloud_deploy_16h52-073020.log](https://github.com/nuagenetworks/nuage-ospdirector/files/5002619/overcloud_deploy_16h52-073020.log)

**Comment by sacckth** [comment]
Openstack version is Queens (RHOSP13)
Nuage version: 6.0.7

**Comment by sjabasti** [comment]
Hi Sergio

Could you share the result of "sudo yum list installed" on the undercloud and the avrs node?

Kind Regards
Steven

**Comment by sacckth** [comment]
UC details:
(undercloud) [stack@uc ~]$ cat /etc/system-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
See attached for yum list installed packages and other packages.
[yum-list-installed.txt](https://github.com/nuagenetworks/nuage-ospdirector/files/5003219/yum-list-installed.txt)
[compute-avrs-environment.yaml.txt](https://github.com/nuagenetworks/nuage-ospdirector/files/5003253/compute-avrs-environment.yaml.txt)
[nuage_overcloud_images.yaml.txt](https://github.com/nuagenetworks/nuage-ospdirector/files/5003254/nuage_overcloud_images.yaml.txt)
[overcloud_images.yaml.txt](https://github.com/nuagenetworks/nuage-ospdirector/files/5003255/overcloud_images.yaml.txt)

Installation with other compute flavors (aka SRIOV/OVS) is OK

**Comment by sacckth** [comment]
I was missing an update in my avrs environment file required on 6.0.7 and 5.4.1U12 as in the documentation example:

https://github.com/nuagenetworks/nuage-ospdirector/blob/OSPD13/nuage-tripleo-heat-templates/environments/compute-avrs-environment.yaml


resource_registry:
  OS::TripleO::Services::NovaComputeAvrs: ../docker/services/nova-compute-avrs.yaml
  OS::TripleO::Services::ComputeNeutronCorePluginNuage: ../puppet/services/neutron-compute-plugin-nuage.yaml      

Thanks Steven for looking into this!
