### ISSUE TITLE
OSPD16: neutron-nuage-config.yaml template inconsistency betwenn documentation example and rpm

### ISSUE THREAD

**Issue by sacckth** [nuagenetworks/nuage-ospdirector#133]
On the example of the neutron-nuage-config.yaml template located on the github:
https://github.com/nuagenetworks/nuage-ospdirector/blob/16.1.20.5.2.1/Documentation/20.5/README.rst#id32
I found what seems to be an inconsistency with a keyword:
```
  HeatEnginePluginDirs: ['/usr/lib/python2.7/site-packages/nuage-heat/']
```
 
The example installed according to the installation guide (from RPM) shows the Python 3 equivalent library:
```
  HeatEnginePluginDirs: ['/usr/lib/python3.6/site-packages/nuage-heat/']
``` 

I assume the latter is the correct one, right?

**Comment by sjabasti** [comment]
Same with
HorizonVhostExtraParams:
    add_listen: true
    priority: 10
    access_log_format: '%a %l %u %t \"%r\" %>s %b \"%%{}{Referer}i\" \"%%{}{User-Agent}i\"'
    aliases: [{'alias': '%{root_url}/static/nuage', 'path': '/usr/lib/python3.6/site-packages/nuage_horizon/static'}, {'alias': '%{root_url}/static', 'path': '/usr/share/openstack-dashboard/static'}]
    directories: [{'path': '/usr/lib/python2.7/site-packages/nuage_horizon', 'options': ['FollowSymLinks'], 'allow_override': ['None'], 'require': 'all granted'}]

will fix

**Comment by sjabasti** [comment]
Merged into OSPD16 branch and will be fixed in next release
