### ISSUE TITLE
OSPD13_VRS_offload Documentatio

### ISSUE THREAD

**Issue by jfargen** [nuagenetworks/nuage-ospdirector#62]
The OSPD13_VRS_offload documentation include references to 6wind packages for AVRS.

**Comment by sunny-verma** [comment]
@jfargen  Can you please elaborate more what exactly is the issue you are reporting here and also please refer to what section in the documentation  ( some link to line# would be useful) so we are on the same page. Thanks,

**Comment by rommelb** [comment]
this is the fact that offload documentation also includes package information for other elements such as DPDK.  He is looking for documentation clearly defining a process model for a specific model.

**Comment by psairam** [comment]
@jfargen, we have updated the doc with the requested changes and it is here https://github.com/nuagenetworks/nuage-ospdirector/blob/OSPD13_VRS_offload/Documentation/5.4.1/README.rst.
