### ISSUE TITLE
Iptables rule

### ISSUE THREAD

**Issue by jfargen** [nuagenetworks/nuage-ospdirector#63]
This is a more succinct and universal iptables rule based on the interface name rather than the ipaddress.

sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

**Comment by sunny-verma** [comment]
Thanks @jfargen for reporting and your suggestion. #69 should accommodate that.

**Comment by sunny-verma** [comment]
I will close this issue as it's being resolved in the OSPD13 branch. 
@jfargen
