### ISSUE TITLE
Update apply_patch.py for Triple0 v8.3.1-18

### ISSUE THREAD

**Issue by jfargen** [nuagenetworks/nuage-ospdirector#68]
Please work to update the apply_patch.py in the OSPD13_VRS_offload branch to tripleo v8.3.1-18. 

stack@tpavcpp4ar101v7uc tripleo-heat-templates-diff]$ sudo python apply_patch.py 
Not supported for openstack-tripleo-heat-templates-8.3.1-18.el7ost.noarch

**Comment by rurena77** [comment]
This is also a blocker for OSPD13 branch. 

[stack@tpavcpp4r1v1uc tripleo-heat-templates-diff]$ rpm -qa openstack-tripleo-heat-templates
openstack-tripleo-heat-templates-8.3.1-18.el7ost.noarch

**Comment by dttocs** [comment]
@jfargen As discussed separately, this will be fixed by removing any patching of openstack-tripleo-heat-templates by the Nuage integration.  This will remove the dependency of Nuage changes on the openstack-tripleo-heat-template version.  See #69.

**Comment by sunny-verma** [comment]
I will close this issue as it's being resolved in the OSPD13 branch. 
@jfargen
