### ISSUE TITLE
Nuage Overcloud Patch Script: Disable GPG Check

### ISSUE THREAD

**Issue by jfargen** [nuagenetworks/nuage-ospdirector#70]
When you run the command without the option for the GPG key, it prints an ERROR saying that --RpmPublicKey or --no_signing_key is being pased.

[root@tpavcpaq096s03 images]# python ./nuage_overcloud_full_patch.py --ImageName="./overcloud-full.qcow2" --RepoName="avrs-5.4.1u4" --RepoBaseUrl="http://192.168.100.1/nuage/telco/vrs-5.4.1u4/" --AVRSBaseUrl="http://192.168.100.1/nuage/telco/avrs-5.4.1u4/" --Version="13"
2019-06-26 21:47:03,057 - root - ERROR - '--RpmPublicKey' or '--no_signing_key' are not passed in image patching command, If verification of Nuage-supplied packages is not required, please restart image patching with the --no_signing_key option.

[root@tpavcpaq096s03 images]# python ./nuage_overcloud_full_patch.py --ImageName="./overcloud-full.qcow2" --RepoName="avrs-5.4.1u4" --RepoBaseUrl="http://192.168.100.1/nuage/telco/vrs-5.4.1u4/" --AVRSBaseUrl="http://192.168.100.1/nuage/telco/avrs-5.4.1u4/" --Version="13" --no_signing_key
usage: nuage_overcloud_full_patch.py [-h] --ImageName IMAGENAME
                                     [--RhelUserName RHELUSERNAME]
                                     [--RhelPassword RHELPASSWORD]
                                     [--RhelPool RHELPOOL]
                                     [--RepoName REPONAME] --RepoBaseUrl
                                     REPOBASEURL [--AVRSBaseUrl AVRSBASEURL]
                                     --Version VERSION
                                     [--RpmPublicKey RPMPUBLICKEY]
                                     [--no-signing-key]
                                     [--ProxyHostname PROXYHOSTNAME]
                                     [--ProxyPort PROXYPORT]
                                     [--logFile LOGFILE]
nuage_overcloud_full_patch.py: error: unrecognized arguments: --no_signing_key

The actual argument that needs to be passed is --no-signing-key instead of what was printed above --no_signing_key

[root@tpavcpaq096s03 images]# python ./nuage_overcloud_full_patch.py --ImageName="./overcloud-full.qcow2" --RepoName="avrs-5.4.1u4" --RepoBaseUrl="http://192.168.100.1/nuage/telco/vrs-5.4.1u4/" --AVRSBaseUrl="http://192.168.100.1/nuage/telco/avrs-5.4.1u4/" --Version="13" --no-signing-key
2019-06-26 21:48:52,923 - root - WARNING - Image patching proceeding with package signature verification disabled. Nuage packages installed will not have package signatures verified.
2019-06-26 21:48:52,926 - root - DEBUG - Verifying pre-requisite packages for script

2019-06-26 21:48:52,958 - root - DEBUG - libguestfs-tools-c-1.38.2-12.el7_6.1.x86_64

2019-06-26 21:48:52,961 - root - DEBUG - Uninstalling packages

2019-06-26 21:49:43,055 - root - DEBUG - [   0.0] Examining the guest ...
[   2.5] Setting a random seed

**Comment by sunny-verma** [comment]
I will close this issue as it's being resolved in the OSPD13 branch. 
@jfargen
