### ISSUE TITLE
nuage_overcloud_full_patch.py: Reset the Machine ID

### ISSUE THREAD

**Issue by jfargen-rh** [nuagenetworks/nuage-ospdirector#88]
When the the nuage_overcloud_full_patch.py script is run and virt-customize is called a machine id is added. 

This can be verified by running the nuage_overcloud_full_patch.py and then copying the /etc/machine-id file out of the image.

[root@server ]# export LIBGUESTFS_BACKEND=direct; /usr/bin/virt-copy-out -a overcloud-full.qcow2 /etc/machine-id .
[root@server images-5.4.1u5]# cat machine-id 
db0b7db09c488fbb506g41b86fa7a39d

This machine-id should be removed using the virt-sysprep tool:
`virt-sysprep --operation machine-id -a overcloud-full.qcow2`

**Comment by sunny-verma** [comment]
Thanks @jfargen-rh. 
https://github.com/nuagenetworks/nuage-ospdirector/pull/86/files should take care of adding this step to our documentation.

**Comment by sunny-verma** [comment]
Merged the changes to Readme. @jfargen-rh  Please let us know if there is anything else I need to add. I will close this issue for now.
